/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.AssetController;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
<<<<<<< HEAD
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
=======
>>>>>>> origin
import model.Asset;

/**
 *
 * @author NMHoang
 */
public class Asset_View extends javax.swing.JFrame {

    public ArrayList<Asset> list;
    DefaultTableModel model;

    /**
     * Creates new form User info_View
     */
    public Asset_View() {
        initComponents();
        this.setLocationRelativeTo(null);
        list = new AssetController().getListAsset();
        model = (DefaultTableModel) tbAsset.getModel();
        showTable(); //hien thi thong tin trong database

    }

    public void showTable() {
        for (Asset a : list) {
            model.addRow(new Object[]{
                a.getMaTS(), a.getTenTS(), a.getLoaiTS(), a.getTtTS(), 1, a.getNguoiGiu(), a.getThoiGianTiepNhan()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    AssetController asCtrl = new AssetController();
    Asset asModal = new Asset();
    int noti;
    JFrame jf;

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelRegis = new javax.swing.JPanel();
        btnUserControl = new javax.swing.JLabel();
        labelUserInfo = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnUserAsset = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        labelHandover = new javax.swing.JPanel();
        btnHandover = new javax.swing.JLabel();
        labelRecall = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        labelExit = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtMaTS = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtTenTS = new javax.swing.JTextField();
        txtLoaiTS = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtNguoiGiu = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cbttTS = new javax.swing.JComboBox<>();
        btnDeleteAsset = new javax.swing.JButton();
        btnAddAsset = new javax.swing.JButton();
        btnChangeAsset = new javax.swing.JButton();
        btnSearchAsset = new javax.swing.JButton();
        btnExcel = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbAsset = new javax.swing.JTable();

        jMenuItem1.setText("jMenuItem1");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 700));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 700));

        jPanel2.setBackground(new java.awt.Color(79, 88, 88));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setPreferredSize(new java.awt.Dimension(250, 700));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 0, 102));
        jPanel3.setPreferredSize(new java.awt.Dimension(250, 100));

        jLabel1.setBackground(new java.awt.Color(255, 0, 0));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Quản lý tài sản");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        labelRegis.setBackground(new java.awt.Color(51, 204, 0));
        labelRegis.setPreferredSize(new java.awt.Dimension(200, 70));
        labelRegis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelRegisMouseClicked(evt);
            }
        });

        btnUserControl.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnUserControl.setText("Quản lý người dùng");

        javax.swing.GroupLayout labelRegisLayout = new javax.swing.GroupLayout(labelRegis);
        labelRegis.setLayout(labelRegisLayout);
        labelRegisLayout.setHorizontalGroup(
            labelRegisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(labelRegisLayout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addComponent(btnUserControl)
                .addGap(0, 22, Short.MAX_VALUE))
        );
        labelRegisLayout.setVerticalGroup(
            labelRegisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(labelRegisLayout.createSequentialGroup()
                .addGap(0, 24, Short.MAX_VALUE)
                .addComponent(btnUserControl)
                .addGap(0, 24, Short.MAX_VALUE))
        );

        labelUserInfo.setBackground(new java.awt.Color(51, 204, 0));
        labelUserInfo.setPreferredSize(new java.awt.Dimension(200, 70));
        labelUserInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelUserInfoMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Quản lý thông tin");

        javax.swing.GroupLayout labelUserInfoLayout = new javax.swing.GroupLayout(labelUserInfo);
        labelUserInfo.setLayout(labelUserInfoLayout);
        labelUserInfoLayout.setHorizontalGroup(
            labelUserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(labelUserInfoLayout.createSequentialGroup()
                .addGap(0, 31, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(0, 31, Short.MAX_VALUE))
        );
        labelUserInfoLayout.setVerticalGroup(
            labelUserInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(labelUserInfoLayout.createSequentialGroup()
                .addGap(0, 24, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(0, 24, Short.MAX_VALUE))
        );

        btnUserAsset.setBackground(new java.awt.Color(255, 255, 255));
        btnUserAsset.setPreferredSize(new java.awt.Dimension(200, 70));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Quản lý tài sản");

        javax.swing.GroupLayout btnUserAssetLayout = new javax.swing.GroupLayout(btnUserAsset);
        btnUserAsset.setLayout(btnUserAssetLayout);
        btnUserAssetLayout.setHorizontalGroup(
            btnUserAssetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnUserAssetLayout.createSequentialGroup()
                .addGap(0, 41, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(0, 41, Short.MAX_VALUE))
        );
        btnUserAssetLayout.setVerticalGroup(
            btnUserAssetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnUserAssetLayout.createSequentialGroup()
                .addGap(0, 24, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(0, 24, Short.MAX_VALUE))
        );

        labelHandover.setBackground(new java.awt.Color(51, 204, 0));
        labelHandover.setPreferredSize(new java.awt.Dimension(200, 70));
        labelHandover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelHandoverMouseClicked(evt);
            }
        });

        btnHandover.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnHandover.setText("Bàn giao tài sản");

        javax.swing.GroupLayout labelHandoverLayout = new javax.swing.GroupLayout(labelHandover);
        labelHandover.setLayout(labelHandoverLayout);
        labelHandoverLayout.setHorizontalGroup(
            labelHandoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(labelHandoverLayout.createSequentialGroup()
                .addGap(0, 37, Short.MAX_VALUE)
                .addComponent(btnHandover)
                .addGap(0, 38, Short.MAX_VALUE))
        );
        labelHandoverLayout.setVerticalGroup(
            labelHandoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(labelHandoverLayout.createSequentialGroup()
                .addGap(0, 24, Short.MAX_VALUE)
                .addComponent(btnHandover)
                .addGap(0, 24, Short.MAX_VALUE))
        );

        labelRecall.setBackground(new java.awt.Color(51, 204, 0));
        labelRecall.setPreferredSize(new java.awt.Dimension(200, 70));
        labelRecall.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelRecallMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Thu hồi tài sản");

        javax.swing.GroupLayout labelRecallLayout = new javax.swing.GroupLayout(labelRecall);
        labelRecall.setLayout(labelRecallLayout);
        labelRecallLayout.setHorizontalGroup(
            labelRecallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(labelRecallLayout.createSequentialGroup()
                .addGap(0, 41, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(0, 42, Short.MAX_VALUE))
        );
        labelRecallLayout.setVerticalGroup(
            labelRecallLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(labelRecallLayout.createSequentialGroup()
                .addGap(0, 24, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(0, 24, Short.MAX_VALUE))
        );

        labelExit.setBackground(new java.awt.Color(51, 204, 0));
        labelExit.setPreferredSize(new java.awt.Dimension(200, 70));
        labelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelExitMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Đăng xuất");

        javax.swing.GroupLayout labelExitLayout = new javax.swing.GroupLayout(labelExit);
        labelExit.setLayout(labelExitLayout);
        labelExitLayout.setHorizontalGroup(
            labelExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(labelExitLayout.createSequentialGroup()
                .addGap(0, 60, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(0, 60, Short.MAX_VALUE))
        );
        labelExitLayout.setVerticalGroup(
            labelExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(labelExitLayout.createSequentialGroup()
                .addGap(0, 24, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(0, 24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 25, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelRecall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelHandover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUserAsset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelUserInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelRegis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 25, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(labelRegis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelUserInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUserAsset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelHandover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelRecall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setMaximumSize(new java.awt.Dimension(1000, 700));
        jPanel11.setMinimumSize(new java.awt.Dimension(1000, 700));
        jPanel11.setPreferredSize(new java.awt.Dimension(1000, 700));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Mã tài sản:");

        txtMaTS.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        txtMaTS.setForeground(new java.awt.Color(102, 102, 102));
        txtMaTS.setToolTipText("");
        txtMaTS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaTSActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Tên tài sản:");

        txtTenTS.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        txtTenTS.setForeground(new java.awt.Color(102, 102, 102));
        txtTenTS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenTSActionPerformed(evt);
            }
        });

        txtLoaiTS.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        txtLoaiTS.setForeground(new java.awt.Color(102, 102, 102));
        txtLoaiTS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoaiTSActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("Loại tài sản:");

        txtNguoiGiu.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        txtNguoiGiu.setForeground(new java.awt.Color(102, 102, 102));
        txtNguoiGiu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNguoiGiuActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("Người giữ:");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setText("Tình trạng TS:");

        cbttTS.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cbttTS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mới", "Đã qua sử dụng", "Đã Hỏng" }));

        btnDeleteAsset.setBackground(new java.awt.Color(51, 153, 255));
        btnDeleteAsset.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnDeleteAsset.setText("Xóa");
        btnDeleteAsset.setMaximumSize(new java.awt.Dimension(100, 40));
        btnDeleteAsset.setMinimumSize(new java.awt.Dimension(100, 40));
        btnDeleteAsset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteAssetActionPerformed(evt);
            }
        });

        btnAddAsset.setBackground(new java.awt.Color(51, 153, 255));
        btnAddAsset.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnAddAsset.setText("Thêm");
        btnAddAsset.setMaximumSize(new java.awt.Dimension(100, 40));
        btnAddAsset.setMinimumSize(new java.awt.Dimension(100, 40));
        btnAddAsset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddAssetMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddAssetMouseEntered(evt);
            }
        });
        btnAddAsset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAssetActionPerformed(evt);
            }
        });

        btnChangeAsset.setBackground(new java.awt.Color(51, 153, 255));
        btnChangeAsset.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnChangeAsset.setText("Sửa");
        btnChangeAsset.setMaximumSize(new java.awt.Dimension(100, 40));
        btnChangeAsset.setMinimumSize(new java.awt.Dimension(100, 40));
        btnChangeAsset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeAssetActionPerformed(evt);
            }
        });

        btnSearchAsset.setBackground(new java.awt.Color(51, 153, 255));
        btnSearchAsset.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnSearchAsset.setText("Tìm kiếm");
        btnSearchAsset.setMaximumSize(new java.awt.Dimension(100, 40));
        btnSearchAsset.setMinimumSize(new java.awt.Dimension(100, 40));
        btnSearchAsset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchAssetActionPerformed(evt);
            }
        });

        btnExcel.setBackground(new java.awt.Color(51, 153, 255));
        btnExcel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnExcel.setText("Xuất Exel");
        btnExcel.setMaximumSize(new java.awt.Dimension(100, 40));
        btnExcel.setMinimumSize(new java.awt.Dimension(100, 40));
        btnExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtTenTS, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMaTS, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbttTS, 0, 200, Short.MAX_VALUE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtLoaiTS, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txtNguoiGiu))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addComponent(btnSearchAsset, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddAsset, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnChangeAsset, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDeleteAsset, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaTS))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenTS))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbttTS, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLoaiTS))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNguoiGiu))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSearchAsset, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteAsset, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddAsset, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChangeAsset, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        txtMaTS.getAccessibleContext().setAccessibleName("");

        tbAsset.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tbAsset.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã TS", "Tên TS", "Loại TS", "Tình trạng TS", "Số lượng", "Người giữ", "Thời gian tiếp nhận"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbAsset.setDragEnabled(true);
        jScrollPane3.setViewportView(tbAsset);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 728, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 752, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaTSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaTSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaTSActionPerformed

    private void txtTenTSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenTSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenTSActionPerformed

    private void txtLoaiTSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoaiTSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLoaiTSActionPerformed

    private void txtNguoiGiuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNguoiGiuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNguoiGiuActionPerformed

    private void btnDeleteAssetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAssetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteAssetActionPerformed

    private void btnAddAssetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAssetActionPerformed

        String date = new String();
        date = LocalDate.now().toString();
        String maTS = txtMaTS.getText();
        String tenTS = txtTenTS.getText();
        String nguoGiu = txtNguoiGiu.getText();
        String loaiTS = txtLoaiTS.getText();
        String ttTS = cbttTS.getSelectedItem().toString();
        System.out.println("");
        if (maTS ==null || tenTS ==null || nguoGiu ==null || loaiTS == null) {
            noti = JOptionPane.showConfirmDialog(btnAddAsset, "Vui lòng điền đầy đủ thông tin", "Alert", JOptionPane.YES_OPTION);
            if (noti == JOptionPane.NO_OPTION) {
                System.exit(0);
            }
        } else {
            // them vao db
            
            if (asCtrl.AddAsset(maTS,tenTS,nguoGiu,loaiTS,ttTS) == true) {
                JOptionPane.showMessageDialog(rootPane, "Add Success !!!");
                list.add(new Asset(maTS, tenTS, loaiTS, nguoGiu, ttTS, 1, loaiTS));
                
            } else {
                JOptionPane.showMessageDialog(rootPane, "Add Fail !!!");
            }
            showResult();
        }
    }//GEN-LAST:event_btnAddAssetActionPerformed

    public void showResult() {
        Asset a = list.get(list.size() - 1);
        model.addRow(new Object[]{
            a.getMaTS(), a.getTenTS(), a.getLoaiTS(), a.getTtTS(), 1, a.getNguoiGiu(), a.getThoiGianTiepNhan()
        });
    }

    private void btnChangeAssetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeAssetActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnChangeAssetActionPerformed

    private void btnSearchAssetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchAssetActionPerformed
        // TODO add your handling code here:
        asModal.setMaTS(txtMaTS.getText());
        asModal.setTenTS(txtTenTS.getText());
        asModal.setNguoiGiu(txtNguoiGiu.getText());
        asModal.setLoaiTS(txtLoaiTS.getText());
        asModal.setTtTS(cbttTS.getSelectedItem().toString());
        if (asModal.maTS.isEmpty() && asModal.tenTS.isEmpty() && asModal.nguoiGiu.isEmpty()) {
            noti = JOptionPane.showConfirmDialog(btnSearchAsset, "Vui lòng nhập ít nhất một thông tin để tìm kiếm", "Alert", JOptionPane.YES_OPTION);
            if (noti == JOptionPane.NO_OPTION) {
                System.exit(0);
            }
        } else {
            asCtrl.SearchAsset();
        }
    }//GEN-LAST:event_btnSearchAssetActionPerformed

    private void btnExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcelActionPerformed
        try {
            // TODO add your handling code here:
            asCtrl.MainExcel();
        } catch (Exception ex) {
            Logger.getLogger(Asset_View.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnExcelActionPerformed

    private void btnAddAssetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddAssetMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddAssetMouseEntered

    private void btnAddAssetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddAssetMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_btnAddAssetMouseClicked

    private void labelRegisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelRegisMouseClicked
        // TODO add your handling code here:
        jf = new Register_View();
        jf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_labelRegisMouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MouseClicked

    private void labelUserInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelUserInfoMouseClicked
        // TODO add your handling code here:
        jf = new Userinfo_View();
        jf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_labelUserInfoMouseClicked

    private void labelHandoverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelHandoverMouseClicked
        // TODO add your handling code here:
        jf = new Handover_Asset_View();
        jf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_labelHandoverMouseClicked

    private void labelRecallMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelRecallMouseClicked
        // TODO add your handling code here:
        jf = new Recall_Asset_View();
        jf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_labelRecallMouseClicked

    private void labelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelExitMouseClicked
        // TODO add your handling code here:
        jf = new Login_View();
        jf.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_labelExitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Asset_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Asset_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Asset_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Asset_View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Asset_View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAsset;
    private javax.swing.JButton btnChangeAsset;
    private javax.swing.JButton btnDeleteAsset;
    private javax.swing.JButton btnExcel;
    private javax.swing.JLabel btnHandover;
    private javax.swing.JButton btnSearchAsset;
    private javax.swing.JPanel btnUserAsset;
    private javax.swing.JLabel btnUserControl;
    private javax.swing.JComboBox<String> cbttTS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JPanel labelExit;
    private javax.swing.JPanel labelHandover;
    private javax.swing.JPanel labelRecall;
    private javax.swing.JPanel labelRegis;
    private javax.swing.JPanel labelUserInfo;
    private javax.swing.JTable tbAsset;
    private javax.swing.JTextField txtLoaiTS;
    private javax.swing.JTextField txtMaTS;
    private javax.swing.JTextField txtNguoiGiu;
    private javax.swing.JTextField txtTenTS;
    // End of variables declaration//GEN-END:variables
}
